sudo: required
language: c python
python: 2.7
os: linux
services:
  - docker
 
env:
  - DOCKER=on LOCAL_NAME=docker-fastqc_local REMOTE_NAME=4dn-dcic/fastqc

install:
  - sudo pip install schema_salad
  - sudo pip install git+https://github.com/SooLee/cwltool.git  # cwltool
script:
  - if [ "$DOCKER" == "on" ]; then
      docker build -t $LOCAL_NAME .;
      . tests/tests.sh;
    fi;

after_success:
  - if [ "$DOCKER" == "on" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      if [ "$TRAVIS_BRANCH" == "master" ]; then
        if [ "$TRAVIS_PULL_REQUEST" != false ]; then
          docker tag $LOCAL_NAME $REMOTE_NAME:$TRAVIS_PULL_REQUEST_BRANCH;
          docker push $REMOTE_NAME:$TRAVIS_PULL_REQUEST_BRANCH;
        else 
          docker tag $LOCAL_NAME $REMOTE_NAME:latest;
          docker push $REMOTE_NAME:latest;
        fi
      fi
    fi
  - echo 'good'
  - date
